# Copyright 2022 Ubuntu
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  zosci-config-repon:
    default: "https://github.com/openstack-charmers/zosci-config.git"
    type: string
  zosci-config-branch:
    default: "master"
    type: string
